### PR TITLE
Add Elastic Cloud to StatusPage

### PR DESCRIPTION
**Pull request by renshuki**
https://cloud-status.elastic.co/

### CODE REVIEW

**Comment by inket** [comment]
Thank you!

**Comment by renshuki** [comment]
@inket You're welcome, thanks for the merge! 🎉

**Comment by renshuki** [comment]
@inket any timing for next App Store release btw? Thanks.

**Comment by inket** [comment]
This weekend, sorry for the delay!

**Comment by renshuki** [comment]
no worry, take your time :)

**Pull request merged**
